function[h_surf,h_contour,axes1,h_annot,h_annot2]= createfigure5(XData1,YData1,CData1,zdata2, annot_str, title1,units,Cmin,Cmax, colmap, xsize,ysize,xmin,xmax,ymin,ymax,unit,LevelList)
%CREATEFIGURE(ZDATA1,YDATA1,XDATA1,CDATA1,ZDATA2)
%  ZDATA1:  surface zdata
%  YDATA1:  surface ydata
%  XDATA1:  surface xdata
%  CDATA1:  surface cdata
%  ZDATA2:  contour z

figure1 = figure('PaperSize',[20 30],...
    'Color',[1 1 1],...
    'Colormap',colmap,...
    'GraphicsSmoothing','off',...
    'Position',[0 0 xsize ysize]);

dx=xmax-xmin;
dy=ymax-ymin;
for i=0:10
    interval = 10^i;
    if(min(dx/10^i,dy/10^i)<10)
        break
    end
end  

plotwidth = 150/xsize; % match transect plot size
plotheight = plotwidth*xsize/dx*dy/ysize;

% axes
axes1 = axes('Parent',figure1,...
    'YTick', ymin:interval:ymax,...
    'XTick', xmin:interval:xmax,...
    'FontSize',12,...
    'FontName','Arial',...
    'CLim',[Cmin Cmax],...
    'Position',[40/xsize (84)/ysize plotwidth plotheight],...
    'Box','on');
% Axes
%xlim(axes1,[-25 3125]);
 xlim(axes1,[xmin xmax]);
% Axes
%ylim(axes1,[-25 9525]);
 ylim(axes1,[ymin ymax]);
hold(axes1,'all');
pbaspect([dx dy 1])


% surface
%surface('Parent',axes1,'ZData',ZData1,'YData',YData1,'XData',XData1,...
%    'LineStyle','none',...
%    'CData', CData1);

h_surf=pcolor(XData1,YData1,CData1);
shading flat;
%shading interp;

% colorbar
%colormap(colmap);
% colorbar('peer',axes1,...
%     'FontSize',9);

% contour
h_contour=contour(XData1,YData1,zdata2,...
    'LineColor',[0.48 0.06 0.92],...
    'LevelList',LevelList,...
    'Parent',axes1,...
    'ShowText','off');

%    'LevelList',[0 0.25 0.5 1 3 5],...
%    'LevelList',[0 0.25 0.5 1 3 5],...
%    'LevelList',[-1 1],...
%    'LevelList',[0 0.5 1 3],...
%     'LevelList',[0 0.2 0.5 3],...

if strcmp(unit,'km')
    % xlabel
    xl1 = xlabel('[km]','FontName','Arial');
    % ylabel
    yl1 = ylabel('[km]','FontName','Arial');
elseif strcmp(unit,'m') 
    % xlabel
    xl1 = xlabel('[m]','FontName','Arial');
    % ylabel
    yl1 = ylabel('[m]','FontName','Arial');
elseif strcmp(unit,'latlon')
    % xlabel
    xl1 = xlabel('Longitude','FontName','Arial');
    % ylabel
    yl1 = ylabel('Latitude','FontName','Arial');
end

yl1.Position(1) = xmin - 0.1*(xmax-xmin);
xl1.Position(2) = xmin - 0.1*(xmax-xmin);

% title
% title(title1,'FontSize',12,'FontName','Arial', 'FontWeight', 'normal');

% Title textbox

annotation(figure1,'textbox',...
    [0.0 574/ysize 1.0 26.25/ysize],...
    'HorizontalAlignment', 'center',...
    'VerticalAlignment', 'middle',...
    'String',title1,...
    'FontName','Arial',...
    'FontSize',16,...
    'FitBoxToText','on',...
    'LineStyle','none');

% colorbar position
% colorbar('Position',[192/xsize (90+37.5+5)/ysize 15/xsize 375/ysize],...
%     'FontSize',9);

% Add dummy bar plot to make legends match colors
% colors -- desired color for each type/class
colors=[colmap((1/4*(Cmax-Cmin)+Cmin)/4*size(colmap, 1),:); ...
        colmap((2/4*(Cmax-Cmin)+Cmin)/4*size(colmap, 1),:); ...
        colmap((3/4*(Cmax-Cmin)+Cmin)/4*size(colmap, 1),:); ...
        colmap((4/4*(Cmax-Cmin)+Cmin)/4*size(colmap, 1),:); ...
        ];
nColors=size(colors,1);                             % make variable so can change easily
labels={'Light';'Carbon';'Nitrogen';'Phosphorus'};
legend_dummy_plot = bar(nan(2,nColors));         % the bar object array for legend
for i=1:nColors
  legend_dummy_plot(i).FaceColor=colors(i,:);
end
lgd=legend(legend_dummy_plot,labels,'Position',[200/xsize (90+37.5+5)/ysize 12/xsize 35/ysize]);
set(lgd, 'ItemTokenSize', [10 10]); 
fontsize(lgd,12,'points')
title(lgd,'Limiting Factor','FontWeight','normal')



% datetime
h_annot=annotation(figure1,'textbox',...
    [0.0 15/ysize 1.0 26.25/ysize],...
    'HorizontalAlignment', 'center',...
    'String',annot_str,...
    'FontName','Arial',...
    'FontSize',14,...
    'FitBoxToText','on',...
    'LineStyle','none');


% subtitle
h_annot2=annotation(figure1,'textbox',...
    [0.0 547/ysize 1.0 26.25/ysize],...
    'HorizontalAlignment', 'center',...
    'String',annot_str,...
    'FontName','Arial',...
    'FontSize',16,...
    'FitBoxToText','on',...
    'LineStyle','none');
